// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrstzonuvlgrelqpsclx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyc3R6b251dmxncmVscXBzY2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mjg5OTYsImV4cCI6MjA2OTIwNDk5Nn0.O1B-kexRVwrATWJqqXzMvoCK0TwDsGw122r2KyWEkGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});